MadLittleMods/node-usb-detection

- README.md
- binding.gyp
- package.json
- src/detection.cpp
- src/detection.h
Add Node v0.12.x support.
Fixes KABA-CCEAC/node-usb-detection#6
- Upgraded all native addon C++ calls.
- Used [nan](https://www.npmjs.com/package/nan)
---
You can depend on it now until the PR gets merged.
```
npm install git://github.com/MadLittleMods/node-usb-detection.git#add-node-v0.12.x-support --save
```
> Add Node v0.12.x support

- CHANGELOG.md
- README.md
- package.json
- Remove install hook to prevent hanging when installing.
- Thanks to @Lange for figuring out the root cause speedily, https://github.com/MadLittleMods/node-usb-detection/pull/47#issuecomment-343714022
- Prepare `usb-detect@1.4.2`
> Remove install hook to prevent hanging - Prepare 1.4.2

- CHANGELOG.md
- README.md
- index.js
- package.json
- src/detection_linux.cpp
- src/detection_mac.cpp
- src/detection_win.cpp
- test/test.js
- Remove side-effects and instead use `usbDetect.startMonitoring()`
- Re-introduce npm `install` hook to use prebuilt binaries
---
Spawned out of discussion here, https://github.com/MadLittleMods/node-usb-detection/pull/47#issuecomment-343714183, where the install was hanging because `prebuild-install` in our npm `install` hook does a `require` to verify things are working and we have side-effects in v1.
> Remove side-effects and instead use startMonitoring()

- .eslintrc
- .gitignore
- doc/debugging-notes.md
- index.js
- package-lock.json
- package.json
- src/detection_linux.cpp
- src/detection_mac.cpp
- src/detection_win.cpp
- test/.eslintrc
- test/dev-helper-test.js
- test/fixtures/requiring-exit-gracefully.js
- test/fixtures/sigint-after-start-monitoring-exit-gracefully.js
- test/fixtures/start-delayed-stop-monitoring-exit-gracefully.js
- test/fixtures/start-stop-monitoring-exit-gracefully.js
- test/lib/child-executor.js
- test/lib/command-runner.js
- test/lib/set-timeout-promise-helper.js
- test/test.js
Mergeable version of https://github.com/MadLittleMods/node-usb-detection/pull/21 from @sarakusha
- Fix https://github.com/MadLittleMods/node-usb-detection/issues/2 (fix 100% CPU on Linux)
- Fix https://github.com/MadLittleMods/node-usb-detection/issues/35 (exit gracefully)
- Remove side-effects when importing package
- This is reproducible if you run `npm test`, go through the manual steps and it just hangs. If you unplug a USB device again, it will throw a segmentation fault.
- Using `usbDetect.stopMonitoring()` has no effect
Testing
- https://nikhilm.github.io/uvbook/threads.html#id1
---
For reference, here is how I tested this PR on Windows 10 with Hyper-V in a Ubuntu 16.04.3 VM.
VirtualBox will BSOD your PC if you have Hyper-V enabled. Otherwise, we could use their slick USB device …
> Fix 100% CPU usage, use non-blocking IO to exit gracefully (remove side-effects)

- src/detection_win.cpp
In AddItemToList function we are using `SPDRP_HARDWAREID` as dictionary key.
This is a problem because if you plug 2 same devices this will overwrite & we will see only 1 device.
If we use `SPDRP_LOCATION_INFORMATION` as key it will be OK.
> Change Device Key to SPDRP_LOCATION_INFORMATION

- src/detection_win.cpp
Fix https://github.com/MadLittleMods/node-usb-detection/issues/36
Add Serial support for Windows OS
---
Alternative to https://github.com/MadLittleMods/node-usb-detection/pull/50
> Add Serial support for Windows OS

- index.js
- package-lock.json
- package.json
- test/lib/child-executor.js
- test/lib/command-runner.js
- test/lib/set-timeout-promise-helper.js
- test/test.js
Node has had native promises since v4 so I don't think bluebird is required.
> Use native Promises

- src/detection_win.cpp
Created a local function to normalize slashes in a device's instance id after a call to SetupDiGetDeviceInstanceId and used it after each necessary call.
Closes https://github.com/MadLittleMods/node-usb-detection/issues/64
> Added Windows backslash normalization for instance id's.

- README.md
Fix https://github.com/MadLittleMods/node-usb-detection/issues/78
As discussed in https://github.com/MadLittleMods/node-usb-detection/issues/78#issuecomment-483892512
I added it to the FAQ section, but wasn't sure if it should live there or the docs for `.find()` proper, lmk if you'd rather it there, or both places.
> Add note about .find requiring .startMonitoring

- index.js
- test/test.js
Fixes #33 by checking if vid or pid are functions, currently if only vid and pid are given the pid is made into a callback.
> Update vid/pid check to check for function

- .travis.yml
- appveyor.yml
- package-lock.json
- package.json
- src/detection.cpp
Closes https://github.com/MadLittleMods/node-usb-detection/issues/80
There seem to be multiple ways to fix the NumberValue error, not sure which is the best/correct one.
I also did not check how this might affect compatibility with older versions of Node.
> Add support for Node 12

- src/detection_win.cpp
Fix https://github.com/MadLittleMods/node-usb-detection/issues/34
Fix deviceName garbled in Windows
> bugfix: deviceName garbled in Windows #34

- index.d.ts
Updated type definitions to node-usb-detection 4.5.0
Old type definitions only allowed `find()` function to return a `Promise` object, if the function was called without parameters.
The updated type definitions now accept `find(vid)` and `find(vid, pid)` as Promise-based functions as well - just as stated in the ReadMe:
> Note: All find calls return a promise even with the node-style callback flavors
_Technically_, the type definitons currently wont allow `find()` to be called with callback function parameter AND returning a Promise either - I could add that too, if desired.
> Updated type definitions for 4.5.0

- package-lock.json
- package.json
[node-abi](https://www.npmjs.com/package/node-abi), which is a dependency of prebuild and prebuild-install, contains the logic for which Node versions `prebuild --all` compiles for and subsequently publishes to GitHub releases.
`package-lock.json` had locked the version of node-abi to a version (2.2.0) from about 2 years ago, leading to a drastically outdated list of precompiled Node versions. This PR uninstalls and then reinstalls prebuild and prebuild-install to pick up the latest version of each as well as the latest version of node-abi.
I haven't been able to get my computer's node-gyp set up properly, so I haven't been able to test this yet. But, if everything works out, I think this should fix #85 and fix #104
> build(prebuild): update prebuild dependencies to latest

- package-lock.json
- package.json
This adds support for Electron 9. Explicitly specifying the node-abi version in `package.json` will make it easier to update node-abi in the future, which adds support for new versions of node and Electron.
> Update prebuild-install, explicitly specify node-abi version

- package.json
I noticed a little problem with the `license` field in the` package.json` when my editor popping up a warning about it:
- Using an object to specify a project's license in `package.json` is deprecated ([source: npm docs](https://docs.npmjs.com/files/package.json#license))
- The URL currently specified in that object is incorrect
This PR fixes these issues by replacing the value of `license` with the SPDX identifier `MIT`, which is recommended by the npm docs linked above
> chore(package.json): use SPDX identifier for MIT in license field

- README.md
As discussed in #118, this PR adds a little Electron-specific subsection to the README's installation instructions that:
- Calls out the fact that usb-detection is a native module
- Links to relevant projects and Electron documentation so Electron end-users of this library know where to look to get things set up properly
> docs(README): add Electron section to install instructions

- src/detection_linux.cpp
Hello,
this commit exposes the devnum and busnum to the library.
I use this to get the path for the device on ubuntu for udev.
Before this change the `device.deviceAddress` and `device.locationId` were set to zero.
---
Related to https://github.com/MadLittleMods/node-usb-detection/issues/8 and https://github.com/MadLittleMods/node-usb-detection/issues/51
> feat: [linux] expose devnum and busnum

- src/detection_linux.cpp
Fix https://github.com/MadLittleMods/node-usb-detection/issues/57
Keeps @antelle's contributions in tree from https://github.com/MadLittleMods/node-usb-detection/pull/138 and incorporates @MadLittleMods and @Julusian's requested changes (I think).
I've confirmed this still fixes the segfault issue on Debian 11/Node 12, but not much beyond that.
~~Furthermore, the tests don't all pass, but it appears they don't in the main repo either.~~
> Fix segfault crash after `stopMonitoring` on Linux v2

- .github/workflows/ci.yml
- package-lock.json
- package.json
Fix GitHub Actions CI failing on Windows runners:
Fix https://github.com/MadLittleMods/node-usb-detection/issues/164
**Before** `windows-latest` -> `windows-2022`:
```
Error: Could not find any Visual Studio installation to use
```
**After** `windows-2019` ✅ 
Default `npm` versions:
- Node.js v12 -> `npm@6.14.16` -> `node-gyp@5.1.0`
- Node.js v14 -> `npm@6.14.16` -> `node-gyp@5.1.0`
- Node.js v16 -> `npm@8.3.1`  -> `node-gyp@5.1.0`
---
```yaml
#
#
- name: 'Install the latest version of node-gyp@^8'
if: ${{ matrix.os != 'Windows' && (matrix.node == '12' || matrix.node == '14') }}
run: npm explore npm/node_modules/npm-lifecycle -g -- npm install node-gyp@^8
- name: 'Install the latest version of node-gyp@^8'
if: ${{ matrix.os != 'Windows' && (matrix.node == '16') }}
run: npm explore …
```
> Fix GitHub Actions CI failing on Windows runners (prebuild failing to build binaries)
